[workspace]
resolver = "2"

members = [
    "2023/day1",
    "2023/day2",
    "2023/day3",
    "2023/day4",
    "2023/day5",
    "2023/day6",
    "2023/day7",
]

[workspace.dependencies]
itertools = "0.12.0"
regex = "1.10.2"
